# docker-compose.yaml
version: "3.8"

services:
  
  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: my-web-frontend
    tty: true
    ports:
      - 3000:3000
    networks:
      - web-network
    volumes:
      - ./frontend:/workspace
      - ./assets:/assets
    command: npm start

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: my-web-backend
    tty: true
    ports:
      - 8000:8000
    networks:
      - web-network
    volumes:
      - ./backend:/workspace
      - ./assets:/assets
    command: uvicorn main:app --host 0.0.0.0 --reload
  
networks:
  web-network:
    driver: bridge